export const SET_FIRST_IMAGE = 'SET_FIRST_IMAGE';
export const SET_FIRST_IMAGE_SIDEBAR = 'SET_FIRST_IMAGE_SIDEBAR';
export const SET_SECOND_IMAGE = 'SET_SECOND_IMAGE';
export const SET_SECOND_IMAGE_SIDEBAR = 'SET_SECOND_IMAGE_SIDEBAR';
export const INITIALIZE_SIDEBAR = 'INITIALIZE_SIDEBAR';
export const EXECUTE_SCRIPT = 'EXECUTE_SCRIPT';
export const CAPTURE_VISIBLE_TAB = 'CAPTURE_VISIBLE_TAB';
